import { existsSync, readFileSync } from "node:fs";
import { config, parse } from "dotenv";
import { createPublicClient, createWalletClient, http, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { bscTestnet } from "viem/chains";

config(); // .env: OWNER_PRIVATE_KEY, AGENT_BASE_URL, optional AGENT_ID / RPC_URL

const devVars = existsSync(".dev.vars") ? parse(readFileSync(".dev.vars")) : {};

export function required(name: string): string {
  const v = process.env[name] ?? devVars[name];
  if (!v) throw new Error(`Missing ${name} (set it in .env, see .env.example)`);
  return v;
}

export const rpcUrl = process.env.RPC_URL ?? "https://bsc-testnet-rpc.publicnode.com";
export const publicClient = createPublicClient({ chain: bscTestnet, transport: http(rpcUrl) });

/** Campaign wallet (owner of the ERC-8004 identity and the HelloFugu listing). */
export function ownerClient() {
  const account = privateKeyToAccount(required("OWNER_PRIVATE_KEY") as Hex);
  return createWalletClient({ chain: bscTestnet, transport: http(rpcUrl), account });
}

/** Agent wallet (signs Venus actions from the Worker); key generated by `npm run keygen` into .dev.vars. */
export const agentAccount = () => privateKeyToAccount(required("AGENT_PRIVATE_KEY") as Hex);

export const baseUrl = () => required("AGENT_BASE_URL").replace(/\/+$/, "");
