import { existsSync, readFileSync } from "node:fs";
import { config, parse } from "dotenv";
import { createPublicClient, createWalletClient, http, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { bscTestnet } from "viem/chains";

config(); // .env: OWNER_PRIVATE_KEY, <PREFIX>AGENT_BASE_URL, optional <PREFIX>AGENT_ID / RPC_URL

const devVars = existsSync(".dev.vars") ? parse(readFileSync(".dev.vars")) : {};

/**
 * Which agent a script acts on: first CLI arg, default "yield" (`npm run register -- treasury`).
 * Per-agent variables carry the prefix: AGENT_PRIVATE_KEY (yield), TREASURY_AGENT_PRIVATE_KEY (treasury).
 * category = FuguRegistry Category enum (2 YIELD, 8 TREASURY).
 */
const AGENTS = {
  yield: { prefix: "", category: 2 },
  treasury: { prefix: "TREASURY_", category: 8 },
} as const;
export type AgentName = keyof typeof AGENTS;

const arg = process.argv[2] ?? "yield";
if (!(arg in AGENTS)) throw new Error(`Unknown agent "${arg}"; use one of: ${Object.keys(AGENTS).join(", ")}`);
export const agentName = arg as AgentName;
export const agentConfig = AGENTS[agentName];

export function required(name: string): string {
  const v = process.env[name] ?? devVars[name];
  if (!v) throw new Error(`Missing ${name} (set it in .env, see .env.example)`);
  return v;
}

/** Per-agent variable: AGENT_ID for yield, TREASURY_AGENT_ID for treasury. */
export function agentVar(name: string, optional = false): string {
  const key = agentConfig.prefix + name;
  return optional ? (process.env[key] ?? devVars[key] ?? "") : required(key);
}

export const rpcUrl = process.env.RPC_URL ?? "https://bsc-testnet-rpc.publicnode.com";
export const publicClient = createPublicClient({ chain: bscTestnet, transport: http(rpcUrl) });

/** Campaign wallet (owner of the ERC-8004 identities and the HelloFugu listings). */
export function ownerClient() {
  const account = privateKeyToAccount(required("OWNER_PRIVATE_KEY") as Hex);
  return createWalletClient({ chain: bscTestnet, transport: http(rpcUrl), account });
}

/** Agent wallet (signs the agent's actions from its Worker); key generated by `npm run keygen` into .dev.vars. */
export const agentAccount = () => privateKeyToAccount(agentVar("AGENT_PRIVATE_KEY") as Hex);

export const baseUrl = () => agentVar("AGENT_BASE_URL").replace(/\/+$/, "");
